config/routes.rb
Rails.application.routes.draw do

  resources :clinic_histories
  resources :patients
  resources :patients
  resources :clinic_histories
  resources :patients, :path => "pascientes"
  resources :roles , :path => "roles"
  resources :cities , :path => "ciudades"
  resources :departments, :path => "departamentos"
  resources :countries, :path => "paises"
  resources :arles, :path => "arl"
  resources :epses, :path => "eps"
  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'
  get 'reporte' => 'users#grafico', as: 'reporte'

  root to: 'pages#home'

  resources :users do
    member do
      get :activate
    end
  end
  resources :products
  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get       'signup', to:   'users#new',  as: :signup
  get       'login',  to:   'sessions#new',       as: :login
  post      'login',  to:   'sessions#create'
  delete    'logout', to:   'sessions#destroy',   as: :logout

end

app/models/arl.rb
class Arl < ActiveRecord::Base

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :department
end

app/models/clinic_history.rb
class ClinicHistory < ActiveRecord::Base
  belongs_to :user
  belongs_to :patient
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :country
end

app/models/eps.rb
class Eps < ActiveRecord::Base
end

app/models/pages.rb
class Pages < ActiveRecord::Base


end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :eps
  belongs_to :arl
  belongs_to :city
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user

  validates :title, :description, :price, :user_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :price, numericality: { less_than_or_equal_to: 999999.99, message:"too high. Nobody will buy it."}
  validates :title, length: {minimum: 3, message: "too short. Must be at least 5 characters long." }
  validates :image_file, allow_blank:true, format: {with: %r{\.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }
end

app/models/rol.rb
class Rol < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  acts_as_messageable
  has_many :products, dependent: :destroy
  before_save { self.email = email.downcase }
  mount_uploader :picture, PictureUploader

  validates :password, presence: true, length: { minimum: 3 }, confirmation: true, if: :new_user?
  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }
  validates :first_name, presence: true, length: { minimum:4 }
  validate :picture_size


    # Metodo para buscar
  def self.search(search)
    where("first_name like '%#{search}%'")
  end

  class << self
    def current_users
      where("#{sorcery_config.last_activity_at_attribute_name} IS NOT NULL") \
      .where("#{sorcery_config.last_logout_at_attribute_name} IS NULL
      OR #{sorcery_config.last_activity_at_attribute_name} > #{sorcery_config.last_logout_at_attribute_name}") \
      .where("#{sorcery_config.last_activity_at_attribute_name} > ? ", sorcery_config.activity_timeout.seconds.ago.utc.to_s(:db))
    end
  end

  def mailboxer_email(object)
    #Check if an email should be sent for that object
      #if true
        return email
      #if false
        #return nil
    end


  private

  def new_user?
    new_record?
  end

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  helper_method :mailbox, :conversation

  before_action :mailbox

 def create
   recipient_emails = conversation_params(:recipients).split(',')
   recipients = User.where(email: recipient_emails).all

   conversation = current_user.send_message(recipients, *conversation_params(:body, :subject)).conversation
 end

 def index
   @conversations ||= @mailbox.inbox.paginate(page: params[:page], per_page: 25)
   @conversationscount ||= current_user.mailbox.inbox.all
   @trash ||= current_user.mailbox.trash.all
 end


 def reply
   current_user.reply_to_conversation(conversation, params[:body])
   redirect_to conversation_path(@conversation)
 end

 def trash
   conversation.move_to_trash(current_user)
   redirect_to :conversations
 end

 def show
   @conversation ||= @mailbox.conversations.find(params[:id])
   conversation.mark_as_read(current_user)
 end

 def untrash
   conversation.untrash(current_user)
   redirect_to :back
 end

  def trashbin
   @conversations ||= @mailbox.inbox.page(params[:page]).per_page(25)
   @conversationscount ||= current_user.mailbox.inbox.all
   @trash ||=  current_user.mailbox.trash.page(params[:page]).per_page(25)
   @trashcount ||= @mailbox.trash.all
 end

 def empty_trash
   current_user.mailbox.trash.each do |conversation|
     conversation.receipts_for(current_user).update_all(:deleted => true)
   end
  redirect_to :conversations
 end

 private

 def mailbox
   @mailbox ||= current_user.mailbox
 end

 def conversation
   @conversation ||= mailbox.conversations.find(params[:id])
 end
end

app/helpers/arles_helper.rb
module ArlesHelper

	def us_states


end


end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/epses_helper.rb
module EpsesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def activated_user
    unless current_user.activation_state == "active" || current_user.admin
      flash[:danger] = "Please activate your account"
      redirect_to products_path
    end
  end

  def correct_user
    unless current_user.admin? || @product = current_user.products.find_by(id: params[:id])
      flash[:danger] = "You don't have the rights to do that!"
      redirect_to products_path
    end
  end

  def current_user?
    unless current_user == User.find_by(id: params[:id]) || current_user.admin
      flash[:danger] = "You don't have the rights to do that!"
      if logged_in?
        redirect_to users_path
      else
        redirect_to root_url
      end
    end
  end
end

app/views/conversations/index.html.erb
<br \> <br \>
<div class="container">
  <div class="well">
    <div class="title">
      <h1>Conversations</h1></div>
      <h2 style="float:right"> <a class="btn btn-default" href="<%= conversations_path %>">  Inbox <%= @conversationscount.count %> </a> <a class="btn btn-default"  href="<%= trashbin_conversations_path %>">  Trash <%= @trash.count %></a> </h2>
    <br>
    <h3> Inbox </h3>
    <br \>
  <table width="900" border="0" cellspacing="0" cellpadding="0"  align="center" class="table table-striped">
  <tr>
    <th scope="col" class="emailTH">SENDER</th>
    <th scope="col" class="emailTH">SUBJECT</th>
    <th scope="col" class="emailTH">DATE</th>
    <th scope="col" class="emailTH"></th>
  </tr>
  <% if @conversations == nil || @conversations.empty? %>
    <i>Your Inbox folder is currently empty</i>
    <%end%>
  <% @conversations.each do |conversation| %>
  <tr>
    <td class="emailsenderTD">
    <% conversation.participants.each do |participant| %>
      <% if participant != current_user %>
          <% if conversation.is_read?(current_user) %> <%= participant.name %>
             <% else %>
             <b> <%= participant.name %> </b>
          <% end %>
        <% end %>
      <% end %>
    </td>
    <td class="emailsubjectTD">
       <% if conversation.is_read?(current_user) %>
        <%= link_to conversation.subject, conversation_path(conversation) %> </td>
        <% else %>
        <b><%= link_to conversation.subject, conversation_path(conversation) %></b> </td>
       <% end %>
    <td class="emailTD">
      <% if conversation.is_read?(current_user) %> <%= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p") %></td>
      <% else %>
      <b> <%= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p") %> </b>
      </td>
      <% end %>
    <td class="emailtrashTD">
      <%= link_to '<i class="fa fa-trash fa-2x"></i>'.html_safe, {:controller => "conversations", :action => "trash", :id => conversation.id}, :title=> "Move to Trash", :method=>'post' %> &nbsp; &nbsp;
    </td>
  </tr>
   <% end %>
</table>
  </span>
  <%= will_paginate @conversations %>
</div>
</div>
</div>

app/views/conversations/show.html.erb
<br \><br \>
<div class="container">
  <div class="well">
    <h1>
      <%= @conversation.subject %>
    </h1>
    <h2>
      <span>A conversation with</span>
      <% @conversation.participants.each do |participant| %>
        <% if participant != current_user %>
          <%= participant.name  %>
        <% end %>
      <% end %>
    </h2>
    <br/>
    <ul style="list-style-type: none">
      <%= content_tag_for(:li, @conversation.receipts_for(current_user)) do |receipt| %>
        <% message = receipt.message %>
        <%= message.sender.name %>:<div class="well">
        <%= simple_format h message.body %></br>
        <span class="timestamp text-muted">Sent</span>
        <span class="timestamp text-muted">
          <%= time_ago_in_words(message.updated_at) %>
        </span>
        <span class="timestamp text-muted">ago.</span></div>
        <br/><br/>
      <% end %>
      <br/>
    </ul>
    <%= render 'messages/form', conversation: @conversation %>
  </div>
</div>

app/views/conversations/trashbin.html.erb
<br \> <br \>
<div class="container">
  <div class="well">
    <div class="title">
      <h1>Conversations</h1></div>
      <h2 style="float:right"> <a class="btn btn-default" href="<%= conversations_path %>"> Inbox <%= @conversations.count %></a>  <a class="btn btn-default"  href="<%= trashbin_conversations_path %>">  Trash <%= @trashcount.count %></a> </h2>
    <br>
    <h3>Trash</h3> &nbsp; &nbsp;<% if @trashcount.count > 0 %><%= button_to 'Empty Trash', 'empty_trash', :confirm => 'Empty trash?', :class => 'btn btn-primary btn-danger' %><%end%>
    <br \>
    <% if @trash == nil || @trash.empty? %>
    <i>Your Trash folder is currently empty</i>
    <%end%>
    <table width="900" border="0" cellspacing="0" cellpadding="0"  align="center" class="table table-striped">
  <tr>
    <th scope="col" class="emailTH">SENDER</th>
    <th scope="col" class="emailTH">SUBJECT</th>
    <th scope="col" class="emailTH">DATE</th>
    <th scope="col" class="emailTH"></th>
  </tr>
    <% @trash.each do |conversation| %>
<tr>
    <td class="emailTD">
    <% conversation.participants.each do |participant| %>
      <% if participant != current_user %>
        <% end %>
        <% if participant != current_user %>
          <b> <%= participant.name %> </b>
          <% end %> <% end %>
    </td>
    <td class="emailsubjectTD"> <%= link_to conversation.subject, conversation_path(conversation) %> </td>
    <td class="emailTD"><%= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p") %></td>
    <td class="emailtrashTD">
      <%= link_to '<i class="fa fa-inbox fa-2x"></i>'.html_safe, {:controller => "conversations", :action => "untrash", :id => conversation.id},  :title => "Move to Inbox", :method=>'post' %>
    </td>
  </tr>
   <% end %>
</table>
  </span>
   <%= will_paginate @trash %>
</div>
</div>
</div>