config/routes.rb
Rails.application.routes.draw do

  resources :clinic_histories
  resources :patients
  resources :patients
  resources :clinic_histories
  resources :patients, :path => "pascientes"
  resources :roles , :path => "roles"
  resources :cities , :path => "ciudades"
  resources :departments, :path => "departamentos"
  resources :countries, :path => "paises"
  resources :arles, :path => "arl"
  resources :epses, :path => "eps"
  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'
  get 'reporte' => 'users#grafico', as: 'reporte'

  root to: 'pages#home'

  resources :users do
    member do
      get :activate
    end
  end
  resources :products
  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get       'signup', to:   'users#new',  as: :signup
  get       'login',  to:   'sessions#new',       as: :login
  post      'login',  to:   'sessions#create'
  delete    'logout', to:   'sessions#destroy',   as: :logout

end

app/models/arl.rb
class Arl < ActiveRecord::Base

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :department
end

app/models/clinic_history.rb
class ClinicHistory < ActiveRecord::Base
  belongs_to :user
  belongs_to :patient
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :country
end

app/models/eps.rb
class Eps < ActiveRecord::Base
end

app/models/pages.rb
class Pages < ActiveRecord::Base


end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :eps
  belongs_to :arl
  belongs_to :city
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user

  validates :title, :description, :price, :user_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :price, numericality: { less_than_or_equal_to: 999999.99, message:"too high. Nobody will buy it."}
  validates :title, length: {minimum: 3, message: "too short. Must be at least 5 characters long." }
  validates :image_file, allow_blank:true, format: {with: %r{\.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }
end

app/models/rol.rb
class Rol < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  acts_as_messageable
  has_many :products, dependent: :destroy
  before_save { self.email = email.downcase }
  mount_uploader :picture, PictureUploader

  validates :password, presence: true, length: { minimum: 3 }, confirmation: true, if: :new_user?
  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }
  validates :first_name, presence: true, length: { minimum:4 }
  validate :picture_size


    # Metodo para buscar
  def self.search(search)
    where("first_name like '%#{search}%'")
  end

  class << self
    def current_users
      where("#{sorcery_config.last_activity_at_attribute_name} IS NOT NULL") \
      .where("#{sorcery_config.last_logout_at_attribute_name} IS NULL
      OR #{sorcery_config.last_activity_at_attribute_name} > #{sorcery_config.last_logout_at_attribute_name}") \
      .where("#{sorcery_config.last_activity_at_attribute_name} > ? ", sorcery_config.activity_timeout.seconds.ago.utc.to_s(:db))
    end
  end

  def mailboxer_email(object)
    #Check if an email should be sent for that object
      #if true
        return email
      #if false
        #return nil
    end


  private

  def new_user?
    new_record?
  end

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:show, :index]
  #before_action :activated_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :activated_user, except: [:show, :index]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(page: params[:page] )
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { flash[:success] = 'Product was successfully created.'
                      redirect_to @product  }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { flash[:success] = 'Product was successfully updated.'
                      redirect_to @product }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { flash[:success] = 'Product was successfully destroyed.'
                    redirect_to products_url
                     }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_file, :price )
    end
end

app/helpers/arles_helper.rb
module ArlesHelper

	def us_states


end


end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/epses_helper.rb
module EpsesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def activated_user
    unless current_user.activation_state == "active" || current_user.admin
      flash[:danger] = "Please activate your account"
      redirect_to products_path
    end
  end

  def correct_user
    unless current_user.admin? || @product = current_user.products.find_by(id: params[:id])
      flash[:danger] = "You don't have the rights to do that!"
      redirect_to products_path
    end
  end

  def current_user?
    unless current_user == User.find_by(id: params[:id]) || current_user.admin
      flash[:danger] = "You don't have the rights to do that!"
      if logged_in?
        redirect_to users_path
      else
        redirect_to root_url
      end
    end
  end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_file %><br>
    <%= f.text_field :image_file %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>
<%= will_paginate %>
<table class="table table-striped table-bordered table-hover" style="width:auto">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image file</th>
      <th>Price</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= truncate(product.description, length: 20) %></td>
        <td><%= product.image_file %></td>
        <td><%= product.price %></td>
        <td><%= product.user.name %></td>
        <td class="col-md-4 btn-group" role="group" aria-label="...">
                <button type="button" class="btn btn-default"><%= link_to 'Show', product %></button>
                <% if logged_in? %>
                  <% if current_user.products.include?(product) || current_user.admin %>
                <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_product_path(product) %></button>
                <button type="button" class="btn btn-default"><%= link_to 'Destroy', product,
                                                                  method: :delete, data: { confirm: 'Are you sure?' } %></button>
                  <% end %>
                <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate %>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image file:</strong>
  <%= @product.image_file %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user.name %>
</p>
<% if logged_in? %>
  <% if current_user.products.include?(@product) || current_user.admin %>
<%= link_to 'Edit', edit_product_path(@product) %> |
  <% end %>
<% end %>
<%= link_to 'Back', products_path %>