config/routes.rb
Rails.application.routes.draw do

  resources :clinic_histories
  resources :patients
  resources :patients
  resources :clinic_histories
  resources :patients, :path => "pascientes"
  resources :roles , :path => "roles"
  resources :cities , :path => "ciudades"
  resources :departments, :path => "departamentos"
  resources :countries, :path => "paises"
  resources :arles, :path => "arl"
  resources :epses, :path => "eps"
  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'
  get 'reporte' => 'users#grafico', as: 'reporte'

  root to: 'pages#home'

  resources :users do
    member do
      get :activate
    end
  end
  resources :products
  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get       'signup', to:   'users#new',  as: :signup
  get       'login',  to:   'sessions#new',       as: :login
  post      'login',  to:   'sessions#create'
  delete    'logout', to:   'sessions#destroy',   as: :logout

end

app/models/arl.rb
class Arl < ActiveRecord::Base

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :department
end

app/models/clinic_history.rb
class ClinicHistory < ActiveRecord::Base
  belongs_to :user
  belongs_to :patient
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :country
end

app/models/eps.rb
class Eps < ActiveRecord::Base
end

app/models/pages.rb
class Pages < ActiveRecord::Base


end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :eps
  belongs_to :arl
  belongs_to :city
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user

  validates :title, :description, :price, :user_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :price, numericality: { less_than_or_equal_to: 999999.99, message:"too high. Nobody will buy it."}
  validates :title, length: {minimum: 3, message: "too short. Must be at least 5 characters long." }
  validates :image_file, allow_blank:true, format: {with: %r{\.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }
end

app/models/rol.rb
class Rol < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  acts_as_messageable
  has_many :products, dependent: :destroy
  before_save { self.email = email.downcase }
  mount_uploader :picture, PictureUploader

  validates :password, presence: true, length: { minimum: 3 }, confirmation: true, if: :new_user?
  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }
  validates :first_name, presence: true, length: { minimum:4 }
  validate :picture_size


    # Metodo para buscar
  def self.search(search)
    where("first_name like '%#{search}%'")
  end

  class << self
    def current_users
      where("#{sorcery_config.last_activity_at_attribute_name} IS NOT NULL") \
      .where("#{sorcery_config.last_logout_at_attribute_name} IS NULL
      OR #{sorcery_config.last_activity_at_attribute_name} > #{sorcery_config.last_logout_at_attribute_name}") \
      .where("#{sorcery_config.last_activity_at_attribute_name} > ? ", sorcery_config.activity_timeout.seconds.ago.utc.to_s(:db))
    end
  end

  def mailboxer_email(object)
    #Check if an email should be sent for that object
      #if true
        return email
      #if false
        #return nil
    end


  private

  def new_user?
    new_record?
  end

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/helpers/arles_helper.rb
module ArlesHelper

	def us_states


end


end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/epses_helper.rb
module EpsesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def activated_user
    unless current_user.activation_state == "active" || current_user.admin
      flash[:danger] = "Please activate your account"
      redirect_to products_path
    end
  end

  def correct_user
    unless current_user.admin? || @product = current_user.products.find_by(id: params[:id])
      flash[:danger] = "You don't have the rights to do that!"
      redirect_to products_path
    end
  end

  def current_user?
    unless current_user == User.find_by(id: params[:id]) || current_user.admin
      flash[:danger] = "You don't have the rights to do that!"
      if logged_in?
        redirect_to users_path
      else
        redirect_to root_url
      end
    end
  end
end

app/views/layouts/_ex_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <ul class="nav navbar-nav pull-right">
            <li><%=link_to current_user.name, current_user %></li>
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
          </ul>
        <% else %>
          <li><%= link_to 'Sign Up', signup_path %></li>
          <li><%= link_to 'Log In', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<!-- Social Footer, Colour Matching Icons -->
<!-- Include Font Awesome Stylesheet in Header -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
<!-- // -->
    <hr>
        <div class="text-center center-block">
            <p class="txt-railway"> <a href="http://www.aerosanidadsas.com/" target="_blank" class="link_pagina">http://www.aerosanidadsas.com</p>
            <br />
                <a href="https://www.facebook.com/bootsnipp" class="icon-footer"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
	            <a href="https://twitter.com/bootsnipp" class="icon-footer"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
	            <a href="https://plus.google.com/+Bootsnipp-page" class="icon-footer"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
	            <a href="mailto:bootsnipp@gmail.com" class="icon-footer"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
<br/><br/><br/>
</div>


<style type="text/css">
.link_pagina{
	color:#20819e !important;
}
.icon-footer:hover{
	background-color: transparent !important;
}
	.social:hover {
     -webkit-transform: scale(1.1);
     -moz-transform: scale(1.1);
     -o-transform: scale(1.1);
 }
 .social {
     -webkit-transform: scale(0.8);
     /* Browser Variations: */
     
     -moz-transform: scale(0.8);
     -o-transform: scale(0.8);
     -webkit-transition-duration: 0.5s;
     -moz-transition-duration: 0.5s;
     -o-transition-duration: 0.5s;
 }

/*
    Multicoloured Hover Variations
*/
 
 #social-fb:hover {
     color: #3B5998;
 }
 #social-tw:hover {
     color: #4099FF;
 }
 #social-gp:hover {
     color: #d34836;
 }
 #social-em:hover {
     color: #f39c12;
 }
</style>

app/views/layouts/_header.html.erb
<style type="text/css"><
@import url(http://fonts.googleapis.com/css?family=Lato:300,400,700|Raleway:400,300,700);
@font-face {

}

</style>    

<style type="text/css">

.opcion {
  position: relative;
  display: inline-block;
  margin: 5px 5px;
  outline: none;
  color: #FFFFFF !important;
  text-decoration: none;
  text-transform: uppercase;
  letter-spacing: 1px;
  font-weight: 400;
  text-shadow: 0 0 1px rgba(255,255,255,0.3);
  font-size: 10px;
}

.opcion:hover,
.opcion:focus {
  outline: none;
}


/* Effect 14: border switch */
.cl-effect-14 a {
  padding: 0 20px;
  height: 45px;
  line-height: 45px;
}

.cl-effect-14 a::before,
.cl-effect-14 a::after {
  position: absolute;
  width: 45px;
  height: 2px;
  background: #fff;
  content: '';
  opacity: 0.2;
  -webkit-transition: all 0.3s;
  -moz-transition: all 0.3s;
  transition: all 0.3s;
  pointer-events: none;
}

.cl-effect-14 a::before {
  top: 0;
  left: 0;
  -webkit-transform: rotate(90deg);
  -moz-transform: rotate(90deg);
  transform: rotate(90deg);
  -webkit-transform-origin: 0 0;
  -moz-transform-origin: 0 0;
  transform-origin: 0 0;
}

.cl-effect-14 a::after {
  right: 0;
  bottom: 0;
  -webkit-transform: rotate(90deg);
  -moz-transform: rotate(90deg);
  transform: rotate(90deg);
  -webkit-transform-origin: 100% 0;
  -moz-transform-origin: 100% 0;
  transform-origin: 100% 0;
}

.cl-effect-14 a:hover::before,
.cl-effect-14 a:hover::after,
.cl-effect-14 a:focus::before,
.cl-effect-14 a:focus::after {
  opacity: 1;
}

.cl-effect-14 a:hover::before,
.cl-effect-14 a:focus::before {
  left: 50%;
  -webkit-transform: rotate(0deg) translateX(-50%);
  -moz-transform: rotate(0deg) translateX(-50%);
  transform: rotate(0deg) translateX(-50%);
}

.cl-effect-14 a:hover::after,
.cl-effect-14 a:focus::after {
  right: 50%;
  -webkit-transform: rotate(0deg) translateX(50%);
  -moz-transform: rotate(0deg) translateX(50%);
  transform: rotate(0deg) translateX(50%);
}



</style>



<nav class="navbar navbar-default color_principal">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <nav class="cl-effect-14">
          <%= link_to 'AeroSanidad', root_path, class: 'opcion navbar-brand' %>
        </nav>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right" >
        <% if current_user %>
          <li><%= link_to 'Pascientes', patients_path %></li>
          <li><%= link_to 'Epses', epses_path %></li>
          <li><%= link_to 'Arles', arles_path %></li>
          <li><%= link_to 'Paises', countries_path %></li>
          <li><%= link_to 'Departamentos', departments_path %></li>
          <li><%= link_to 'Ciudades', cities_path %></li>
          <li><%= link_to 'Roles', roles_path %></li>

        
        


            <li><%= link_to "Users", users_path %></li>
            <li role="presentation" class="dropdown">
              <a  class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Inbox', conversations_path %></li>
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Log Out', logout_path, method: :delete %></li>

              </ul>
            </li>

        <% else %>
          <li><%= link_to 'Registrarte', signup_path %></li>
          <li><%= link_to 'Ingresar', login_path %></li>
        <% end %>
      </ul>
      
     
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>jStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">

    <%= render 'layouts/header' %>

    <% if current_user %>
      <% if current_user.activation_state == "pending" %>
        <div class="alert alert-danger" style="text-align:center">Please activate your account.</div>
      <% end %>
    <% end %>
    <div>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" style="text-align:center">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </div>

    <% if logged_in? %>
    <%= render 'shared/current_users' %>
    <% end %>

    <%= render 'layouts/footer' %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>